package io.github.jdubois.bootui.sample.catalog;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class SampleTransactionScenarios {

    static final long SLOW_TRANSACTION_MILLIS = 650;

    private final ProductRepository products;
    private final SampleNestedTransactionStep nestedStep;

    public SampleTransactionScenarios(ProductRepository products, SampleNestedTransactionStep nestedStep) {
        this.products = products;
        this.nestedStep = nestedStep;
    }

    @Transactional(readOnly = true)
    public long commit() {
        return products.count();
    }

    @Transactional(readOnly = true)
    public long slowCommit() {
        long count = products.count();
        try {
            Thread.sleep(SLOW_TRANSACTION_MILLIS);
        } catch (InterruptedException interrupted) {
            Thread.currentThread().interrupt();
            throw new IllegalStateException("Transaction sample was interrupted", interrupted);
        }
        return count;
    }

    @Transactional
    public void rollBack() {
        products.count();
        throw new SampleTransactionRollbackException();
    }

    @Transactional(readOnly = true)
    public long nested() {
        return nestedStep.run();
    }
}

final class SampleTransactionRollbackException extends RuntimeException {

    SampleTransactionRollbackException() {
        super("Expected rollback generated by the transaction sample");
    }
}
