package io.github.jdubois.bootui.micronaut.serde;

import io.github.jdubois.bootui.core.dto.*;
import io.github.jdubois.bootui.micronaut.web.LoggersController;
import io.github.jdubois.bootui.micronaut.web.McpServerController;
import io.micronaut.serde.annotation.SerdeImport;

/**
 * Declares a Micronaut Serde introspection for every type the BootUI console puts on the wire, so the
 * adapter serializes correctly under {@code micronaut-serde-jackson} as well as under
 * {@code micronaut-jackson-databind}.
 *
 * <p><strong>Why this class exists.</strong> The shared core DTOs are immutable records with no annotations
 * at all — a deliberate architecture invariant, because {@code bootui-core} is consumed by the Spring
 * (Jackson 3), Quarkus (Jackson 2) and Micronaut adapters and must never depend on a JSON library. Jackson
 * databind is happy with that: it reflects over the record at runtime. Micronaut Serde is not, and cannot
 * be — it is reflection-free by design and writes only types for which the compiler produced a
 * {@code BeanIntrospection}. Without those introspections every {@code /bootui/api/**} response failed with
 * <em>"No serializable introspection present for type … Consider adding @Serdeable"</em>, which made the
 * console unusable on the JSON stack a new Micronaut 4 application gets by default.
 *
 * <p>{@link SerdeImport} is the escape hatch built for exactly this shape of problem: it makes an external
 * type serializable from the outside, without touching the type. Declaring the imports here — in the
 * adapter, the only module that knows a JSON stack exists — keeps {@code bootui-core} annotation-free while
 * {@code micronaut-serde-processor} generates the introspections into this module's jar at compile time.
 *
 * <p><strong>Why the whole DTO package, not just the types the controllers name.</strong> A handful of
 * endpoints answer {@code HttpResponse<?>}, and the CLI bridge answers a tool payload typed {@code Object},
 * so the set of DTOs reachable through method signatures is not an upper bound on what actually gets
 * serialized. The rule this class follows is therefore the only one a test can check without guessing:
 * <em>every record in {@code io.github.jdubois.bootui.core.dto} is imported</em>, plus the request records
 * the controllers declare for their own bodies. {@code BootUiSerdeImportsTest} fails the build when a new
 * DTO, or a type reachable from an imported one, is missing.
 *
 * <p><strong>Cost when the host is on Jackson databind.</strong> None that is observable.
 * {@code micronaut-serde-api} is a {@code provided} dependency, so it is not forced onto the application;
 * the annotations below are then simply not loadable at runtime, which the JVM ignores, and the generated
 * introspections sit unused next to Jackson's reflective path. The wire bytes are unchanged either way,
 * which is what keeps the shared Vue UI and the conformance contract identical across all four stacks.
 *
 * <p><strong>Why every import carries {@link AlwaysInclude}.</strong> An introspection alone makes a DTO
 * writable; it does not decide <em>which</em> of its fields get written. Serde's global
 * {@code serde.serialization.inclusion} defaults to {@code NON_EMPTY}, which would drop exactly the empty
 * lists, empty maps and nulls the console's wire contract requires. The mix-in pins the always-include
 * policy onto each imported type at compile time, scoped to BootUI's own DTOs so the host application's
 * inclusion setting still governs its own responses — the Serde counterpart of the runtime Jackson mix-in
 * resolver {@link io.github.jdubois.bootui.micronaut.json.BootUiJsonInclusionCustomizer} installs on the
 * databind stack. {@code BootUiSerdeImportsTest} fails the build if an import is missing it.
 *
 * <p>The class is never instantiated and wires up no bean: it is a compile-time declaration only.
 */
@SerdeImport(value = ActionBusyResult.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ActivationStatus.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ActivityEntryDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ActivityKpiDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ActivityPageInfo.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ActivityPersistenceOptionDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ActivitySwitchRequest.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ActivitySwitchResult.class, mixin = AlwaysInclude.class)
@SerdeImport(value = AiChatDetailDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = AiChatSummaryDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = AiOverviewDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = AiTokenBucketDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = AiTokenSeriesDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = AiToolCallDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = AiVectorOpDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ArchitectureReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ArchitectureRuleResultDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ArchitectureScanStatusDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ArchitectureSeverityCountDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = BeanList.class, mixin = AlwaysInclude.class)
@SerdeImport(value = BeanSummary.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CacheClearRequest.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CacheClearResult.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CacheDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CacheManagerDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CacheMetricsDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CacheOperationDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CacheReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CacheStatisticsDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CacheTierDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CliServerStatus.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CliToolInfo.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ConditionCounts.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ConditionEntry.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ConditionsReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ConfigOverrideRequest.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ConfigOverrideResult.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ConfigPropertyDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ConfigPropertySuggestionDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ConfigReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CopilotActivityBucket.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CopilotActivityEvent.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CopilotDashboardDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CopilotEventListDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CopilotInsightCounts.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CopilotMetricCount.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CopilotRawEventDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CopilotSessionDetail.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CopilotSessionListDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CopilotSessionSummary.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CopilotTurn.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CracFindingDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CracGeneratedFileDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CracInstallAllResultDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CracInstallResultDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CracReadinessReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CracRuntimeStatusDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CracScanStatusDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = CracSeverityCountDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = DatabaseAdvisorDataSourceDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = DatabaseAdvisorDiagnosticDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = DatabaseAdvisorReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = DatabaseAdvisorRuleResultDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = DatabaseAdvisorScanStatusDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = DatabaseAdvisorSeverityCountDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = DependenciesReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = DependencyDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = DependencyScanStatusDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = DependencySeverityCountDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = DependencyVulnerabilityDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = DevServiceDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = DevServiceLogReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = DevServicePortDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = DevServiceRestartResult.class, mixin = AlwaysInclude.class)
@SerdeImport(value = DevServicesReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = DevToolsActionResult.class, mixin = AlwaysInclude.class)
@SerdeImport(value = DevToolsRestartRequest.class, mixin = AlwaysInclude.class)
@SerdeImport(value = DevToolsStatus.class, mixin = AlwaysInclude.class)
@SerdeImport(value = DismissedRulesDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = EmailAttachmentDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = EmailMessageDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = EmailsReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ErrorContractEntryDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ErrorContractLinkDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ErrorContractReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ExceptionCauseDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ExceptionDetailDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ExceptionFrameDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ExceptionGroupDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ExceptionOccurrenceDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ExceptionStatusUpdateRequest.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ExceptionsReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = FaultToleranceEventDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = FaultTolerancePolicyDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = FaultTolerancePolicyMetricsDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = FaultTolerancePolicySettingDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = FaultToleranceReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = FlywayActionRequest.class, mixin = AlwaysInclude.class)
@SerdeImport(value = FlywayActionResult.class, mixin = AlwaysInclude.class)
@SerdeImport(value = FlywayDatabaseDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = FlywayMigrationDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = FlywayReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = GitHubCopilotUsageDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = GitHubCredentialDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = GitHubDashboardReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = GitHubDependabotAlertDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = GitHubIssueBucketDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = GitHubIssueDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = GitHubMetricDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = GitHubPullRequestDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = GitHubQuotaDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = GitHubRepositoryDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = GitHubSecuritySignalDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = GitHubWorkflowDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = GitHubWorkflowRunDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = GraalVmDependencyDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = GraalVmDockerfileDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = GraalVmFindingDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = GraalVmInstallAllResultDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = GraalVmInstallResultDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = GraalVmMetadataSummaryDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = GraalVmReadinessReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = GraalVmScanProgressDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = GraalVmScanStatusDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = GraalVmSeverityCountDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HealthNodeDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HealthSetupStepDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HeapClassHistogramEntryDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HeapDumpCaptureStatusDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HeapDumpFileDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HeapDumpReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HibernateCacheRegionStatisticsDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HibernateReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HibernateRuleResultDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HibernateScanStatusDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HibernateSeverityCountDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HibernateStatisticsDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HibernateStatisticsReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HikariPoolDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HikariPoolSnapshotDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HikariPoolsReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HttpExchangeDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HttpExchangesReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HttpHeaderDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HttpProbeRequest.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HttpProbeResponse.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HttpSessionActionRequest.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HttpSessionActionResult.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HttpSessionAttributeDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HttpSessionDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = HttpSessionsReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = JmsMessageDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = JmsReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = KafkaMessageDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = KafkaReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = KubernetesMemoryRecommendationDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = LiquibaseActionRequest.class, mixin = AlwaysInclude.class)
@SerdeImport(value = LiquibaseActionResult.class, mixin = AlwaysInclude.class)
@SerdeImport(value = LiquibaseChangeSetDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = LiquibaseDatabaseDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = LiquibaseReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = LiveActivityReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = LiveMemoryReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = LogLineDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = LoggerDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = LoggersReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = MappingDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = MappingsReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = McpServerStatus.class, mixin = AlwaysInclude.class)
@SerdeImport(value = McpToolInfo.class, mixin = AlwaysInclude.class)
@SerdeImport(value = MemoryCalculationDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = MemoryPoolDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = MemoryReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = MemoryRuleResultDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = MemoryScanStatusDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = MemorySeverityCountDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = MemorySummaryDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = MetricAvailableTagDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = MetricDetailDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = MetricGroupDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = MetricMeasurementDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = MetricMeterDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = MetricProvenanceDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = MetricSampleDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = MetricTagDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = MetricsReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = OverviewDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = PageMetadata.class, mixin = AlwaysInclude.class)
@SerdeImport(value = PanelDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = PanelsReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = PentestingCoverageDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = PentestingFindingDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = PentestingReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = PentestingScanStatusDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = PentestingSeverityCountDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ProfileSourceDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ProfilesReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = RabbitMessageDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = RabbitReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = RepositoriesReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = RepositoryDetailDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = RepositoryDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = RepositoryMethodDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = RequestProfileDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = RequestProfileExceptionDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = RequestProfileSecurityDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = RequestProfileTimingDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = RestApiReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = RestApiRuleResultDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = RestApiScanStatusDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = RestApiSeverityCountDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = RestClientTraceEntryDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = RestClientTraceGroupDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = RestClientTraceRecordingRequest.class, mixin = AlwaysInclude.class)
@SerdeImport(value = RestClientTraceReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = RestClientTraceStatsDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ScheduledReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ScheduledTaskDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SecurityLogDataDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SecurityLogEventDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SecurityLogTypeSummaryDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SecurityLogsReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SecurityReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SecurityRuleResultDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SecurityScanStatusDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SecuritySeverityCountDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ServiceMapEdgeDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ServiceMapInteractionDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ServiceMapNodeDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ServiceMapReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ServiceMapTruncationDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SpanAttributeDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SpanDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SpanEventDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SpringReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SpringRuleResultDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SpringScanStatusDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SpringSecurityAuthDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SpringSecurityEndpointDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SpringSecurityEndpointsReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SpringSecurityExplainDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SpringSecurityFilterChainDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SpringSecurityReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SpringSeverityCountDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SqlAttributionBucketDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SqlRouteAttributionDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SqlRouteRankingDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SqlRouteStatementDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SqlStatementRankingDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SqlTraceEntryDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SqlTraceGroupDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SqlTraceInsightsReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SqlTraceRecordingRequest.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SqlTraceReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SqlTraceStatsDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = SqlTraceWindowDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = StartupReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = StartupStepDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = TagDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ThreadDumpReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ThreadInfoDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = ThreadStateCountDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = TraceDetailDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = TraceSummaryDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = TracesReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = TransactionEntryDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = TransactionRecordingRequest.class, mixin = AlwaysInclude.class)
@SerdeImport(value = TransactionReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = TransactionStatsDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = WebSocketActivityEntryDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = WebSocketCallbackDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = WebSocketCaptureRequest.class, mixin = AlwaysInclude.class)
@SerdeImport(value = WebSocketEndpointDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = WebSocketReport.class, mixin = AlwaysInclude.class)
@SerdeImport(value = WebSocketSessionDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = WebSocketStatsDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = WebSocketSubscriptionDto.class, mixin = AlwaysInclude.class)
@SerdeImport(value = LoggersController.LevelUpdateRequest.class, mixin = AlwaysInclude.class)
@SerdeImport(value = McpServerController.ToggleRequest.class, mixin = AlwaysInclude.class)
public final class BootUiSerdeImports {

    private BootUiSerdeImports() {}
}
